version: "3"

services:

  lb:
    image: haproxy:2.1
    ports:
      - "8000:8080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg

  client:
    build:
      context: moerphous
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./moerphous:/moerphous
    depends_on:
      - lb

  app1:
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file:
      - .env

  app2:
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file:
      - .env

  app3:
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file:
      - .env

  app4:
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file:
      - .env
